# Generated by Django 5.2.7 on 2025-10-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name', 'father_name'],
                'indexes': [models.Index(fields=['first_name'], name='django_app__first_n_2f5a18_idx'), models.Index(fields=['last_name'], name='django_app__last_na_86f777_idx'), models.Index(fields=['phone_number'], name='django_app__phone_n_5c2b5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'indexes': [models.Index(fields=['title'], name='django_app__title_31a5f5_idx'), models.Index(fields=['salary'], name='django_app__salary_2139ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['last_name', 'first_name', 'father_name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
                ('client_id', models.ManyToManyField(to='django_app.client', verbose_name='Клиент')),
                ('trainer_id', models.ManyToManyField(to='django_app.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('expiry_date', models.DateField(verbose_name='Срок истечения')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='django_app__expiry__f4fe1a_idx'), models.Index(fields=['title'], name='django_app__title_4cebbc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['first_name'], name='django_app__first_n_1c6323_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['last_name'], name='django_app__last_na_884c63_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['phone_number'], name='django_app__phone_n_abc276_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['start_time'], name='django_app__start_t_40d79d_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['end_time'], name='django_app__end_tim_091939_idx'),
        ),
    ]
