# Generated by Django 5.2.7 on 2025-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='father_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='father_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
